---
title: "Article 3 :The effects of Ascaris lumbroides in a Pregnant Woman and 6 Year Old Girl"
description: |
  In this case,biliary ascariasis can be associated with cystic duct obstruction, gallbladder dilation, acute cholecystitis, acute cholangitis, obstructive jaundice, and biliary colic
author:
  - name: NDOUNKANG Maurice Carlos
    url: {}
date: 11-18-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

## Vocabulary  
|Ascaris lumbricoides;                                         |important and prevalent geo-helminth infection                                                                                                                                                                                            |
| ------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
|Gallbladder                                                    |dilation of the oragan below liver                                                                                                                                                                                                        |
|Pregnancy                                                      |Perforation of gallbladder in the pregnant women                                                                                                                                                                                          |
|High parasite burden                                           |worm aggregation in the intestinen, obstruction                                                                                                                                                                                           |
|Under-developed countries                                      |high prevalence of parasitic infections  due to weak socioeconomic status                                                                                                                                                                                                                                                                                                                      |
|volvulus                                                       |intussusception of the foci                                                                                                                                                                                                                                                                                                                                                                    |

## Analysis table 

|Researchers                  |Tarbiat Modares University, Khatam Al-Nabieen University,Tarbiat Modares University,Indira Gandhi Institute for Child Health: Kabul Afghanistan. (Lead autor: Abdolhossein DALIM)                                                                                                                                                                                                                                    |
| ---------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|Published in?                | Open access Journal at http://ijpa.tums.ac.ir                                                                                                                                                                                                                         |
|General topic                | Gallbladder Perforation Due to Ascaris lumbricoides in a Pregnant Woman and 6 Year Old Girl.                                                                                                                                                                                                                                                                                                                                  |
|Procedure/what was examined                               | In the ascariasis abdominal pain, anorexia, nausea, vomiting, fever, dehydration and abdominal distension are the most common symptoms of the disease. Moreover, intestinal obstruction may happen due to the high burden of parasite in children (6-8) years.The related manifestations are pneumonia and intestinal, appendicular, hepatobiliary and pancreatic ascariasis. In pregnancy, the risk of biliary ascariasis increases because of the high level of progesterone and estrogen hormones that influence Oddi sphincter, as previously proved in animal models; These hormones facilitate the migration of worms into biliary ducts.In case of jejunal obstruction with multiple masses, enterotomy and worm removal is the method of choice. Whenever the intestinal wall is thin, for instance, in volvulus cases, milking is avoided due to serosal tears and enterotomy would be better.                                                                                                                                                                                                                                                                                                                                                                                                                  |
| Conclusions/discovery        |  In case of bowel obstruction, dilated and airfilled intestinal loops are observed along with several air-fluid      levels, indicating the railway track sign.Today, the control of ascariasis is not as difficult as before, since the availability of anthelmintic drugs. The main key to eliminating ascariasis in the country is the elevation of sewage system and the other organizations related to disposal of human feces.                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Remaining questions          | Could they have forms of resistance of the parasite Ascaris lumbricoides against treatment with antihelminthic drugs?.                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
