---
title: "Article 1 : The effects of Ascaris lumbroides parasites in the humain"
author:
  - name: "NDOUNKANG Maurice Carlos"
date: 10-23-2019
categories:
  - "Ascaris lumbricoides"
  - "humans parasite"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


! [Credit: Alex Dissanayake Getty Images](https://www.gettyimages.be/detail/foto/ascaris-lumbricoides in intestion for human) ]
(image/where-s-my-Ascaris lymbricoides.jpg)


## Vocabulary
Ascariasis is non-endemic regions. An absence of travel to endemic regions in an individual’s medical history does not exclude the possibility of ascariasis
allergic diseases. Allergic sensitization to Ascaris,however, explained a significant proportion of wheezing among rural schoolchildren  
ascaris infectious. Poverty, illiteracy, poor hygiene, scarcity of potable water, humid  tropical climate, are all  factors associated with ascaris parasitic infestation.
Homeostatis. that measured in unstimulated cultures of peripheral blood leukocytes.
Sensitization to Ascaris. presence of anti‐Ascaris IgE.

## Analysis table 

## Researchers 
University of London, London, UK, Universidad Internacional del Ecuador (lead author: Philip J. Cooper). 
University Medical Centre, ZA Leiden, The Netherlands (lead author:  Hermelijn H. Smits).

## Published
The Balkan Medical Journal published by Galenos Publishing House (04/07/2019). 
wileyonlinelibrary.com/journal/pim (12/09/2019).

## General topic 
The ascaris infections have been associated with significant disability and mortality, particularly in children.                       

## Procedure/what was examined
Ascaris lumbricoides infections have been associated with a stronger regulation of the immune response that can be measured in vitro either at homeostatis.Ascaris are of specific interest to investigations on allergy-related diseases due to the immunological parallels between these two conditions. Both are associated with T helper 2 (Th2) cell induction, high levels of immunoglobulin E (IgE) and the involvement of immune cells such as mast cells, basophils and eosinophil.The researchers has emphasized also the importance of host genetics in determining host immune regulation, risk of atopy and susceptibility to helminths|   

## Conclusions/discovery
The impact of ascariasis on the inception and evolution of allergic diseases such as asthma is part of the long co- evolutionary history of helminths and humans and deserves more investigation. The sensitization to Ascaris  was a consistent risk factor for wheeze and asthma.the studies on immune mechanisms have illustrated how helminth infections can induce immune regulatory responses that may protect against allergic immune responses.

##  Remaining questions
Could this development of allergic sensitization to Ascaris lead to benign asthmatic disease ? Ascaridiosis could be develop yhe forms of resistance to anthelmintic drugs?. 

<https://www.scientificamerican.com/article/wheres-my-elephant-high-tech-collars-track-wildlife-in-real-time1/?redirect=1>




