---
title: "article 7: Interaction of  mucin12 in Ascaris lumbricoides and the human small intestine"
description: |
  A short description of the post.
author:
  - name: NDOUNKANG Maurice Carlos
    url: {}
date: 02-28-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Vocabulary

| host-parasite relationship                            | Ascaris lumbricoides live in their preferred environment (small intestine) in human                                                                                                                                                                                                                                                                                                                                                   |
| -------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------- |
| antigenicity                                           |antibodies were observed in the mucous secretory organs and intestinal canal of A. lumbricoides                                                                                                                                 |
| host immune system                                    | attacked the immune system of host.                                                                                                                                                                           |
| Mucin12 expression by helminths                       | mechanism to evade immunological detection                                                                                                                                |
## Analysis table
                                                                                                                                                            
| Researchers?                                   |  Kansai Medical University, Molecular & Biochemical Parasitology 227 (2019) 19–24, (lead author, I. Hayashi, E-mail addresses: hayashi@oita-nhs.ac.jp)                                                                                                                                                                                                                                                                                                                                                                                       |
| ---------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Published in?                                   |  journal homepage: www.elsevier.com/locate/molbiopara (January, 2019)                                                                                                                                                                                                                                                                                                                                             |
| General topic?                                   | Shared expression of mucin12 in Ascaris lumbricoides and the human small intestine                                                                                                                                                                                                                                                                                                                                                         |
| Procedure/what was examined?                     |the Infection begins when mature A. lumbricoides eggs are orally ingested. Once they reach the small intestine, they hatch, and the larvae invade the intestinal walls, They rupture the alveoli, bronchus, and trachea, enabling them to return to the small intestine. Ascaris lumbricoides and checked their antigenicity against patients. the researchers examined the existence of a substance similar to Ascaris lumbricoides antigen in human intestinal mucosa and recognized more antigenic substances in the cortical laminae and basal laminae of the cuticles of Asacris lumbricoides.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| Conclusions/discovery ?                         |These results suggested that the outside surface of A. lumbricoides might be covered with mucous mucin12 that was secreted by them, These data suggest that expression of mucin12  by Ascaris lumbricoides may be one mechanism through which the parasite evades immunological detection within the mammalian host.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| Remaining questions?                           |Could A. lumbricoides prevent the attack on the host's immune system by secreting mucin12, which has a common antigenicity? could they have other mechanisms used by A. lumbricoides to evade host immunity.?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
