---
title: "The effects of Ascaris lumbroides parasites in the human"
description: |
  A short description of the post.  Ascariasis as well as other helminth infections, is expected to influence the clinical presentation of allergic diseases such as asthma.Indeed, several clinical and experimental works have shown an important impact either increasing or suppressing symptoms, and the same effects have been detected on the underlying immune responses
author:
  - name: NDOUNKANG Maurice Carlos
    url: {}
date: 11-04-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


## Vocabulary  
Ascaris lumbricoides | it's an intestinal parasite of humans
Acariasis| human infected with Ascaris often show no symptoms, regardless of the species of worm
Immunoglobulin E (IgE)| the allergenic activity of Ascaris IgE- binding molecular components and the immunological and clinical influences of ascariasis on asthma
Asthma symptoms| the impact of ascariasis on the inception and evolution of allergic diseases 
Esophagogastroduodenoscopy |
Ascaris lumbricoides is cosmopolitan| Thus, ascariasis is a perfect example of an environmental disease. 


## Analysis table 


## Researchers 
University Krasnodar Russia (lead author: Pavel P Poliako). University of London, London, UK, Universidad Internacional del Ecuador (lead author: Philip J. Cooper). University of Cartagena, Cartagena, Colombia( lead author: Philip Cooper). University School of Medicine, Oranjestad, ABW , University of Benghazi, LBY,(lead author: Azhar Hussain). University Medical Centre, ZA Leiden, The Netherlands (lead author:  Hermelijn H. Smits)


## Published 
The Balkan Medical Journal published by Galenos Publishing House (04/07/2019). wileyonlinelibrary.com/journal/pim (12/09/2019).             wileyonlinelibrary.com/journal/pim (02/10/2019). Cureus (06/13/2019) wileyonlinelibrary.com/journal/pim (18/07/2019)

## General topic                                                                                                    
The effects of Ascaris lumbricoides on allergy are likely to be determined by history of exposure over the life- course and by interactions with a wide variety of other infectious and non- infectious factors

##  Procedure/what was examined 
The pathological problems associated with Ascaris lumbricoides infection can be examined in four specific stages; larval migration; adults worms in the small intestine;  complications and  allergic reactions.The migrating larvae provoke inflammatory reactions in the intestinal mucosa, liver and lungs. Some of them become trapped and immobilised by eosinophils, leading to granuloma formation. In the lungs, the larvae moving from the blood capillaries into the air spaces puncture the capillaries resulting in haemorrhage and oedema of the alveoli. Alveolar sacs become filled with serous exudateThere is infiltration of the peri-bronchial tissues with eosinophils and neutrophils with increased mucous production in the bronchi. This gives rise to cough, high fever, and bronchial asthma. This condition, regarded as Loeffler effect, results in transient lung infiltration with blood eosinophilia, and is frequently caused by Ascaris larvae migrating through the lungs

## Conclusions/discovery                                                                                           
Transmission is through the faecal-oral route; eggs are ingested following contact with fecally or sludge contaminated food and/or soil, or the deliberate act of eating contaminated soil,scaris lumbricoides is cosmopolitan in distribution,  A. lumbricoides thrives in places where the soil is warm and humid, sanitation is poor and poverty and ignorance prevail.The distribution of the global burden of ascariasis shows that South America, Central America and the Caribbean host 8.3%, Africa and the Middle East, 16.7% as well as Central and Southeast Asia and the Oceania region 75% of cases. Ascariasis is prevalent in at least 150 of the 218 countries of the world

## Remaining questions                                                                                           | 
Could   Ascaris lumbricoides infection may be induce regulatory immune responses that can protect human to against allergic immune responses? health education could help to reduce exponentially the risk of Ascaris lumbricoides infestation ?



<https://www.scientificamerican.com/article/wheres-my-Ascaris-lubricoides-that-infect-human/?redirect=1>
